// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final_project;

namespace final_project.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191203111843_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("final_project.Models.Entities.Category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parent_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("parent_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = "1",
                            name = "Chăm sóc da",
                            parent_id = "1"
                        },
                        new
                        {
                            id = "2",
                            name = "Trang điểm",
                            parent_id = "2"
                        },
                        new
                        {
                            id = "3",
                            name = "Chống nắng",
                            parent_id = "1"
                        },
                        new
                        {
                            id = "4",
                            name = "Dưỡng ẩm",
                            parent_id = "1"
                        },
                        new
                        {
                            id = "5",
                            name = "Mặt nạ",
                            parent_id = "1"
                        },
                        new
                        {
                            id = "6",
                            name = "Nước hoa hồng",
                            parent_id = "1"
                        },
                        new
                        {
                            id = "7",
                            name = "Tinh chất dưỡng",
                            parent_id = "1"
                        },
                        new
                        {
                            id = "8",
                            name = "Chăm sóc môi",
                            parent_id = "2"
                        },
                        new
                        {
                            id = "9",
                            name = "Kem nền",
                            parent_id = "2"
                        },
                        new
                        {
                            id = "10",
                            name = "Mascara",
                            parent_id = "2"
                        },
                        new
                        {
                            id = "11",
                            name = "Phấn phủ",
                            parent_id = "2"
                        },
                        new
                        {
                            id = "12",
                            name = "Son",
                            parent_id = "2"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Check_paid_shop", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date_expired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_paid")
                        .HasColumnType("datetime2");

                    b.Property<int>("money")
                        .HasColumnType("int");

                    b.Property<string>("shop_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("shop_id")
                        .IsUnique()
                        .HasFilter("[shop_id] IS NOT NULL");

                    b.ToTable("Check_paid_shop");

                    b.HasData(
                        new
                        {
                            id = "1",
                            date_expired = new DateTime(2019, 12, 3, 18, 18, 42, 41, DateTimeKind.Local).AddTicks(1624),
                            date_paid = new DateTime(2019, 12, 3, 18, 18, 42, 38, DateTimeKind.Local).AddTicks(9648),
                            money = 200000,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "2",
                            date_expired = new DateTime(2019, 12, 3, 18, 18, 42, 41, DateTimeKind.Local).AddTicks(4455),
                            date_paid = new DateTime(2019, 12, 3, 18, 18, 42, 41, DateTimeKind.Local).AddTicks(4383),
                            money = 200000,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "3",
                            date_expired = new DateTime(2019, 12, 3, 18, 18, 42, 41, DateTimeKind.Local).AddTicks(4518),
                            date_paid = new DateTime(2019, 12, 3, 18, 18, 42, 41, DateTimeKind.Local).AddTicks(4514),
                            money = 200000,
                            shop_id = "3"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Color", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            id = "1",
                            name = "Đỏ"
                        },
                        new
                        {
                            id = "2",
                            name = "Hồng"
                        },
                        new
                        {
                            id = "3",
                            name = "Trắng"
                        },
                        new
                        {
                            id = "4",
                            name = "Đen"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Comment", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("user_id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            id = "1",
                            contents = "Đồ cùi quá",
                            product_id = "1",
                            rate = 3,
                            user_id = "1"
                        },
                        new
                        {
                            id = "2",
                            contents = "Oke",
                            product_id = "1",
                            rate = 4,
                            user_id = "2"
                        },
                        new
                        {
                            id = "3",
                            contents = "Oke",
                            product_id = "1",
                            rate = 5,
                            user_id = "3"
                        },
                        new
                        {
                            id = "4",
                            contents = "Oke",
                            product_id = "1",
                            rate = 5,
                            user_id = "4"
                        },
                        new
                        {
                            id = "5",
                            contents = "Đồ cùi quá",
                            product_id = "2",
                            rate = 3,
                            user_id = "1"
                        },
                        new
                        {
                            id = "6",
                            contents = "Oke",
                            product_id = "2",
                            rate = 4,
                            user_id = "2"
                        },
                        new
                        {
                            id = "7",
                            contents = "Oke",
                            product_id = "2",
                            rate = 5,
                            user_id = "3"
                        },
                        new
                        {
                            id = "8",
                            contents = "Oke",
                            product_id = "3",
                            rate = 5,
                            user_id = "4"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Order", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date_create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_paid")
                        .HasColumnType("datetime2");

                    b.Property<string>("payment_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("receiver_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("payment_id");

                    b.HasIndex("receiver_id")
                        .IsUnique()
                        .HasFilter("[receiver_id] IS NOT NULL");

                    b.HasIndex("user_id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            id = "1",
                            date_create = new DateTime(2019, 12, 3, 18, 18, 42, 62, DateTimeKind.Local).AddTicks(6667),
                            date_paid = new DateTime(2019, 12, 3, 18, 18, 42, 62, DateTimeKind.Local).AddTicks(7926),
                            payment_id = "1",
                            receiver_id = "1",
                            status = 1,
                            total = 900000,
                            user_id = "1"
                        },
                        new
                        {
                            id = "2",
                            date_create = new DateTime(2019, 12, 3, 18, 18, 42, 63, DateTimeKind.Local).AddTicks(2685),
                            date_paid = new DateTime(2019, 12, 3, 18, 18, 42, 63, DateTimeKind.Local).AddTicks(2732),
                            payment_id = "1",
                            receiver_id = "3",
                            status = 2,
                            total = 800000,
                            user_id = "3"
                        },
                        new
                        {
                            id = "3",
                            date_create = new DateTime(2019, 12, 3, 18, 18, 42, 63, DateTimeKind.Local).AddTicks(2844),
                            date_paid = new DateTime(2019, 12, 3, 18, 18, 42, 63, DateTimeKind.Local).AddTicks(2849),
                            payment_id = "1",
                            receiver_id = "4",
                            status = 3,
                            total = 1000000,
                            user_id = "4"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Order_detail", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("order_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("product_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.ToTable("Order_details");

                    b.HasData(
                        new
                        {
                            id = "1",
                            order_id = "1",
                            price = 900000,
                            product_id = "1",
                            quantity = 1
                        },
                        new
                        {
                            id = "2",
                            order_id = "2",
                            price = 800000,
                            product_id = "2",
                            quantity = 1
                        },
                        new
                        {
                            id = "3",
                            order_id = "3",
                            price = 1000000,
                            product_id = "3",
                            quantity = 1
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Payment_method", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Payment_methods");

                    b.HasData(
                        new
                        {
                            id = "1",
                            name = "Thanh toán khi nhận hàng"
                        },
                        new
                        {
                            id = "2",
                            name = "Paypal"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Product", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cat_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("product_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("shop_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("cat_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = "1",
                            cat_id = "3",
                            description = "Kem trang điểm chống nắng Innisfree SPF50+ PA++++ được rất nhiều chị em trên khắp thế giới yêu thích là bởi chất kem nhẹ bẫng, mềm mượt, tạo nên một lớp trang điểm hoàn hảo mà vẫn có chỉ số chống nắng cao ngất ngưởng, có thể bảo vệ làn da tuyệt đối dưới ánh nắng mặt trời ngày hè",
                            image = "ChongNang1.jpg",
                            price = 900000,
                            product_name = "Kem chống nắng Innisfree SPF50+ PA++++",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "2",
                            cat_id = "3",
                            description = "Có khả năng bảo vệ da mạnh mẽ dưới tác động của ánh nắng mặt trời, cung cấp độ ẩm cho da, làn da trắng hồng rạng rỡ, đầy sức sống",
                            image = "ChongNang3.jpg",
                            price = 800000,
                            product_name = "Kem Chống Nắng Dịu Nhẹ Với Chiết xuất Từ Thiên Nhiên Black Rouge Cica Green Sun Cream SPF50+/PA++++",
                            quantity = 150,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "3",
                            cat_id = "3",
                            description = "Kem chống nắng vật lý, chăm sóc da mẫn cảm, dưỡng trắng",
                            image = "ChongNang2.jpg",
                            price = 1000000,
                            product_name = "Kem chống nắng Uriage Bariesun SPF50+ - Kem chống nắng tốt nhất giúp tái tạo da và ngừa da hư tổn",
                            quantity = 50,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "4",
                            cat_id = "3",
                            description = "Sản phẩm đến từ Hàn Quốc chất lượng cao",
                            image = "ChongNang4.jpg",
                            price = 1500000,
                            product_name = "Kem chống nắng kiêm kem lót nâng tone da A'pieu Pure Block Tone-Up Sun Base SPF50+ PA+++",
                            quantity = 50,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "5",
                            cat_id = "3",
                            description = "Sản phẩm đến từ Hàn Quốc chất lượng cao",
                            image = "ChongNang5.jpg",
                            price = 900000,
                            product_name = "Kem Chống Nắng Dạng Gel Chống Tia Hồng Ngoại, Giảm Nhiệt Độ Tức Thì Make Prem UV Defense Me Blue Ray Sun Gel SPF50/PA++++",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "6",
                            cat_id = "3",
                            description = "Sản phẩm đến từ Hàn Quốc chất lượng cao",
                            image = "ChongNang6.jpg",
                            price = 800000,
                            product_name = " Kem Chống Nắng Dưỡng Trắng Da Milky Dress Aqua Sun Cream",
                            quantity = 150,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "7",
                            cat_id = "3",
                            description = "Giúp làm dịu da, kháng viêm, giảm kích ứng da ngay lần đầu sử dụng.",
                            image = "ChongNang7.jpg",
                            price = 1000000,
                            product_name = "Kem Chống Nắng Chiết Xuất Măng Cụt It's Skin Tropical Sun Gel Mangosteen SPF50+/PA++++ ",
                            quantity = 50,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "8",
                            cat_id = "3",
                            description = "Sản phẩm đến từ Hàn Quốc chất lượng cao",
                            image = "ChongNang8.jpg",
                            price = 1500000,
                            product_name = "Xịt Chống Nắng Làm Dịu Da Giảm Nhiệt Tức Thì Mediheal Labocare Ceramatica Sun Spray",
                            quantity = 50,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "9",
                            cat_id = "4",
                            description = "Sản phẩm đến từ Hàn Quốc chất lượng cao",
                            image = "DuongAmSau.jpg",
                            price = 450000,
                            product_name = "Serum  dưỡng ẩm Innisfree",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "10",
                            cat_id = "4",
                            description = "Sản phẩm đến từ Hàn Quốc chất lượng cao",
                            image = "DuongAmSauDanHoi.jpg",
                            price = 700000,
                            product_name = "Serum dưỡng ẩm đàn hồi Innisfree",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "11",
                            cat_id = "4",
                            description = "Sản phẩm đến từ Hàn Quốc chất lượng cao",
                            image = "DuongAm.jpg",
                            price = 600000,
                            product_name = "Kem Dưỡng Ẩm Và Giữ Ẩm Chuyên Sâu Với Chiết Xuất Từ Gừng Và Mật Ong Innisfree Ginger Honey Cream",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "12",
                            cat_id = "5",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "MatNaDatSet.jpg",
                            price = 400000,
                            product_name = "Mặt nạ dưỡng da đất sét",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "13",
                            cat_id = "5",
                            description = "Không chỉ là loại quả bổ dưỡng, cam còn có tác dụng làm đẹp da tuyệt vời và lành tính nhất. Cam chứa nhiều vitamin A, B, E, Kali…giúp cung cấp dưỡng chất nuôi dưỡng da. Đồng thời cam cung cấp độ ẩm cho da giúp da khỏe mạnh và đàn hồi tốt",
                            image = "MatNaCam.jpg",
                            price = 900000,
                            product_name = "Mặt nạ dưỡng da từ quả Cam",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "14",
                            cat_id = "5",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "MatNa1.jpg",
                            price = 300000,
                            product_name = "Mặt Nạ Vitamin Dưỡng Trắng Da By Wishtrend Natural Vitamin 21.5% Enhancing Sheet Mask",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "15",
                            cat_id = "5",
                            description = "Táo được biết đến là top thực phẩm giàu chất chống oxy hóa, giúp ngăn quá trình lão hóa",
                            image = "MatNa2.jpg",
                            price = 500000,
                            product_name = "Mặt Nạ Làm Sáng Da, Loại Bỏ Tế Bào Chết Chiết Xuất Từ TáoROUNDLAB Apple Peeling Mask ",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "16",
                            cat_id = "5",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "MatNa4.jpg",
                            price = 270000,
                            product_name = "Mặt Nạ Ngủ Dưỡng Trắng Chiết Xuất Từ Trái Thanh Yên Some By Mi Yuja Niacin 30 Days Miracle Brightening Sleeping Mask",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "17",
                            cat_id = "8",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "MatNa3.jpg",
                            price = 200000,
                            product_name = "Mặt Nạ Ngủ Môi Laneige Lip Sleeping Mask",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "18",
                            cat_id = "6",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "NuocHoaHong1.jpg",
                            price = 820000,
                            product_name = "Nước hoa hồng Innisfree",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "19",
                            cat_id = "6",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "NuocHoaHong2.jpg",
                            price = 900000,
                            product_name = "Nước hoa hồng Tea Tree Cica",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "20",
                            cat_id = "8",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "ChamSocMoi2.jpg",
                            price = 210000,
                            product_name = "Son Dưỡng Môi Innisfree",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "21",
                            cat_id = "8",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "DuongMoi1.jpg",
                            price = 110000,
                            product_name = "Son Dưỡng Innisfree Canola Honey Lip Balm",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "22",
                            cat_id = "8",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "DuongMoi2.jpg",
                            price = 810000,
                            product_name = "Son Dưỡng Môi Có Màu Innisfree Glow Tint Lip Balm",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "23",
                            cat_id = "8",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "DuongMoi3.jpg",
                            price = 170000,
                            product_name = "Son Dưỡng 16Brand Fruit Chu Petit Lip Balm",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "24",
                            cat_id = "8",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "DuongMoi4.jpg",
                            price = 920000,
                            product_name = "Mặt Nạ Ngủ Môi Carenel Berry Lip Night Mask",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "25",
                            cat_id = "8",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "DuongMoi5.jpg",
                            price = 280000,
                            product_name = "Mặt Nạ Ngủ Môi Chiết Xuất Rau Má A'pieu Madecassoside Lip Sleeping Mask 20g",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "26",
                            cat_id = "9",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "KemNen1.jpg",
                            price = 670000,
                            product_name = "Kem nền Innisfree",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "27",
                            cat_id = "9",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "KemNen2.jpg",
                            price = 100000,
                            product_name = "Kem nền Power Perfection BB cream",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "28",
                            cat_id = "9",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "KemNen3.jpg",
                            price = 800000,
                            product_name = "Kem Nền Siêu Lì, Lâu Trôi A'pieu BB Maker Long Wear SPF30 PA+++",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "29",
                            cat_id = "9",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "KemNen4.jpg",
                            price = 700000,
                            product_name = "Kem Nền Che Phủ Hoàn Hảo, Giúp Da Bóng Khỏe, Rạng Rỡ Suốt 24 Tiếng Etude House Double Lasting Serum Foundation SPF25 PA++",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "30",
                            cat_id = "9",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "KemNen5.jpg",
                            price = 300000,
                            product_name = "Kem Nền Che Phủ Tốt, Lâu Trôi I'm Meme I'm Genius Foundation All Cover",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "31",
                            cat_id = "10",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Mascara1.jpg",
                            price = 200000,
                            product_name = "Mascara Làm Dày Mi Không Lem Missha 4D Mascara",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "32",
                            cat_id = "10",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Mascara.jpg",
                            price = 100000,
                            product_name = "Mascara Siêu Dày Mi Innisfree Super Volumecara ",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "33",
                            cat_id = "10",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Mascara2.jpg",
                            price = 150000,
                            product_name = "Mascara Chân Mày Missha Color Wear Browcara",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "34",
                            cat_id = "10",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Mascara3.jpg",
                            price = 350000,
                            product_name = "Mascara Chuốt Mi Cong Vút Tự Nhiên, Chống Trôi Etude House Lash Perm Curl Fix Mascara",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "35",
                            cat_id = "10",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Mascara4.jpg",
                            price = 180000,
                            product_name = "Mascara Giúp Dài Mi Chống Trôi Missha Length Boost Cara",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "36",
                            cat_id = "10",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Mascara5.jpg",
                            price = 210000,
                            product_name = "Mascara Chống Trôi , Làm Cong Mi Tự Nhiên Shionle Fixing High Heel Cara",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "37",
                            cat_id = "11",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "PhanPhu1.jpg",
                            price = 230000,
                            product_name = "Phấn phủ Play 101 Setting",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "38",
                            cat_id = "11",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "PhanPhu2.jpg",
                            price = 340000,
                            product_name = "Phấn phủ LANEIGE",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "39",
                            cat_id = "11",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "PhanPhu3.jpg",
                            price = 290000,
                            product_name = "Phấn Phủ Bột Kiềm Dầu Innisfree No Sebum Mineral Powder",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "40",
                            cat_id = "11",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "PhanPhu4.jpg",
                            price = 320000,
                            product_name = "Phấn Phủ Bột Kiềm Dầu, Cố Định Lớp Makeup A'pieu Mineral 100 HD Powder",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "41",
                            cat_id = "11",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "PhanPhu5.jpg",
                            price = 450000,
                            product_name = "Phấn Phủ Dạng Nén Kiềm Dầu, Che Phủ Lỗ Chân Lông A'pieu Oil Control Film Pact",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "42",
                            cat_id = "11",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "PhanPhu6.jpg",
                            price = 290000,
                            product_name = "Phấn Phủ Kiềm Dầu I'm Meme I'm Oil Cut Pact ",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "43",
                            cat_id = "12",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "SonLi.jpg",
                            price = 430000,
                            product_name = "Son Thỏi Lì Merzy The First Lipstick",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "44",
                            cat_id = "12",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "SonThoi.jpg",
                            price = 850000,
                            product_name = "Son Thỏi Lì ROM",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "45",
                            cat_id = "12",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Son1.jpg",
                            price = 350000,
                            product_name = "Son Kem Lì Black Rouge Air Fit Velvet Tint",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "46",
                            cat_id = "12",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Son2.jpg",
                            price = 210000,
                            product_name = "Son kem lì cực nhẹ môi Romand Zero Velvet Tint",
                            quantity = 100,
                            shop_id = "1"
                        },
                        new
                        {
                            id = "47",
                            cat_id = "12",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Son3.jpg",
                            price = 370000,
                            product_name = "Son Kem Lì Black Rouge Air Fit Velvet",
                            quantity = 100,
                            shop_id = "2"
                        },
                        new
                        {
                            id = "48",
                            cat_id = "12",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Son4.jpg",
                            price = 800000,
                            product_name = "Son Tint Lì Lâu Trôi Black Rouge Power Proof Matte Tint ",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "49",
                            cat_id = "7",
                            description = "Sản phẩm chất lượng cao đến từ Hàn Quốc",
                            image = "Tinhchat.jpg",
                            price = 800000,
                            product_name = "Tinh chất dưỡng ",
                            quantity = 100,
                            shop_id = "3"
                        },
                        new
                        {
                            id = "50",
                            cat_id = "3",
                            description = "Kem trang điểm chống nắng Innisfree SPF50+ PA++++ được rất nhiều chị em trên khắp thế giới yêu thích là bởi chất kem nhẹ bẫng, mềm mượt, tạo nên một lớp trang điểm hoàn hảo mà vẫn có chỉ số chống nắng cao ngất ngưởng, có thể bảo vệ làn da tuyệt đối dưới ánh nắng mặt trời ngày hè",
                            image = "ChongNang1.jpg",
                            price = 900000,
                            product_name = "Kem chống nắng Innisfree SPF50+ PA++++",
                            quantity = 100,
                            shop_id = "1"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Product_Color", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("color_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("color_id");

                    b.HasIndex("product_id");

                    b.ToTable("product_Colors");

                    b.HasData(
                        new
                        {
                            id = "1",
                            color_id = "3",
                            product_id = "1"
                        },
                        new
                        {
                            id = "2",
                            color_id = "3",
                            product_id = "2"
                        },
                        new
                        {
                            id = "3",
                            color_id = "3",
                            product_id = "3"
                        },
                        new
                        {
                            id = "4",
                            color_id = "3",
                            product_id = "4"
                        },
                        new
                        {
                            id = "5",
                            color_id = "3",
                            product_id = "5"
                        },
                        new
                        {
                            id = "6",
                            color_id = "3",
                            product_id = "6"
                        },
                        new
                        {
                            id = "7",
                            color_id = "3",
                            product_id = "7"
                        },
                        new
                        {
                            id = "8",
                            color_id = "3",
                            product_id = "8"
                        },
                        new
                        {
                            id = "9",
                            color_id = "3",
                            product_id = "9"
                        },
                        new
                        {
                            id = "10",
                            color_id = "3",
                            product_id = "10"
                        },
                        new
                        {
                            id = "11",
                            color_id = "3",
                            product_id = "11"
                        },
                        new
                        {
                            id = "12",
                            color_id = "3",
                            product_id = "12"
                        },
                        new
                        {
                            id = "13",
                            color_id = "3",
                            product_id = "13"
                        },
                        new
                        {
                            id = "14",
                            color_id = "3",
                            product_id = "14"
                        },
                        new
                        {
                            id = "15",
                            color_id = "3",
                            product_id = "15"
                        },
                        new
                        {
                            id = "16",
                            color_id = "3",
                            product_id = "16"
                        },
                        new
                        {
                            id = "17",
                            color_id = "1",
                            product_id = "18"
                        },
                        new
                        {
                            id = "18",
                            color_id = "2",
                            product_id = "19"
                        },
                        new
                        {
                            id = "19",
                            color_id = "1",
                            product_id = "20"
                        },
                        new
                        {
                            id = "20",
                            color_id = "1",
                            product_id = "21"
                        },
                        new
                        {
                            id = "21",
                            color_id = "2",
                            product_id = "22"
                        },
                        new
                        {
                            id = "22",
                            color_id = "1",
                            product_id = "23"
                        },
                        new
                        {
                            id = "23",
                            color_id = "2",
                            product_id = "24"
                        },
                        new
                        {
                            id = "24",
                            color_id = "4",
                            product_id = "25"
                        },
                        new
                        {
                            id = "25",
                            color_id = "4",
                            product_id = "26"
                        },
                        new
                        {
                            id = "26",
                            color_id = "4",
                            product_id = "27"
                        },
                        new
                        {
                            id = "27",
                            color_id = "4",
                            product_id = "28"
                        },
                        new
                        {
                            id = "28",
                            color_id = "4",
                            product_id = "29"
                        },
                        new
                        {
                            id = "29",
                            color_id = "4",
                            product_id = "30"
                        },
                        new
                        {
                            id = "30",
                            color_id = "3",
                            product_id = "37"
                        },
                        new
                        {
                            id = "31",
                            color_id = "3",
                            product_id = "38"
                        },
                        new
                        {
                            id = "32",
                            color_id = "3",
                            product_id = "39"
                        },
                        new
                        {
                            id = "33",
                            color_id = "3",
                            product_id = "40"
                        },
                        new
                        {
                            id = "34",
                            color_id = "3",
                            product_id = "41"
                        },
                        new
                        {
                            id = "35",
                            color_id = "3",
                            product_id = "42"
                        },
                        new
                        {
                            id = "36",
                            color_id = "1",
                            product_id = "43"
                        },
                        new
                        {
                            id = "37",
                            color_id = "1",
                            product_id = "44"
                        },
                        new
                        {
                            id = "38",
                            color_id = "2",
                            product_id = "45"
                        },
                        new
                        {
                            id = "39",
                            color_id = "2",
                            product_id = "46"
                        },
                        new
                        {
                            id = "40",
                            color_id = "2",
                            product_id = "47"
                        },
                        new
                        {
                            id = "41",
                            color_id = "1",
                            product_id = "48"
                        },
                        new
                        {
                            id = "42",
                            color_id = "1",
                            product_id = "50"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Receiver", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Receivers");

                    b.HasData(
                        new
                        {
                            id = "1",
                            address = "193 NLB",
                            email = "damhoangbuu@gmail.com",
                            fullname = "Đàm Văn Hoàng Bửu",
                            phone = "0898237228"
                        },
                        new
                        {
                            id = "2",
                            address = "193 NLB",
                            email = "buithikieu@gmail.com",
                            fullname = "Bùi Thị Kiều",
                            phone = "0975191672"
                        },
                        new
                        {
                            id = "3",
                            address = "193 NLB",
                            email = "tranthusuong@gmail.com",
                            fullname = "Trần Thu Sương",
                            phone = "0975197462"
                        },
                        new
                        {
                            id = "4",
                            address = "193 NLB",
                            email = "nguyentruongson@gmail.com",
                            fullname = "Nguyễn Trường Sơn",
                            phone = "0988191672"
                        },
                        new
                        {
                            id = "5",
                            address = "193 NLB",
                            email = "damhoangbuu@gmail.com",
                            fullname = "Đàm Văn Hoàng Bửu"
                        },
                        new
                        {
                            id = "6",
                            address = "193 NLB",
                            email = "damhoangbuu@gmail.com",
                            fullname = "Đàm Văn Hoàng Bửu",
                            phone = "0898237228"
                        },
                        new
                        {
                            id = "7",
                            address = "193 NLB",
                            email = "damhoangbuu@gmail.com",
                            fullname = "Đàm Văn Hoàng Bửu",
                            phone = "0898237228"
                        },
                        new
                        {
                            id = "8",
                            address = "193 NLB",
                            email = "damhoangbuu@gmail.com",
                            fullname = "Đàm Văn Hoàng Bửu",
                            phone = "0898237228"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Shop", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_accont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("user_id")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            id = "1",
                            address = "193 NLB",
                            email = "buithikieu@gmail.com",
                            name = "Shop mỹ phẩm bà Kèo",
                            payment_accont = "abcxyz",
                            user_id = "2"
                        },
                        new
                        {
                            id = "2",
                            address = "194 NLB",
                            email = "votuonghuan@gmail.com",
                            name = "Ông Huân Vlog",
                            payment_accont = "abcxyz",
                            user_id = "7"
                        },
                        new
                        {
                            id = "3",
                            address = "195 NLB",
                            email = "nguyentruongson@gmail.com",
                            name = "Bé Sơn Parody",
                            payment_accont = "abcxyz",
                            user_id = "8"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = "1",
                            address = "193 NLB",
                            email = "damhoangbuu@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 1,
                            user_name = "Đàm Văn Hoàng Bửu"
                        },
                        new
                        {
                            id = "2",
                            address = "193 NLB",
                            email = "buithikieu@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 2,
                            user_name = "Bùi Thị Kiều"
                        },
                        new
                        {
                            id = "3",
                            address = "193 NLB",
                            email = "tranthusuong@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 3,
                            user_name = "Trần Thu Sương"
                        },
                        new
                        {
                            id = "4",
                            address = "193 NLB",
                            email = "tranphuquy@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 3,
                            user_name = "Trần Phú Quy"
                        },
                        new
                        {
                            id = "5",
                            address = "193 NLB",
                            email = "tranchivi@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 3,
                            user_name = "Trần Chí Vĩ"
                        },
                        new
                        {
                            id = "6",
                            address = "193 NLB",
                            email = "trananhthu@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 3,
                            user_name = "Trần Thị Anh Thư"
                        },
                        new
                        {
                            id = "7",
                            address = "193 NLB",
                            email = "votuonghuan@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 2,
                            user_name = "Võ Tường Huân"
                        },
                        new
                        {
                            id = "8",
                            address = "193 NLB",
                            email = "nguyentruongson@gmail.com",
                            password = "123456",
                            phone = "0898237228",
                            role = 2,
                            user_name = "Nguyễn Trường Sơn"
                        });
                });

            modelBuilder.Entity("final_project.Models.Entities.Category", b =>
                {
                    b.HasOne("final_project.Models.Entities.Category", null)
                        .WithMany("Categories")
                        .HasForeignKey("parent_id");
                });

            modelBuilder.Entity("final_project.Models.Entities.Check_paid_shop", b =>
                {
                    b.HasOne("final_project.Models.Entities.Shop", "Shop")
                        .WithOne("Check_Paid_Shop")
                        .HasForeignKey("final_project.Models.Entities.Check_paid_shop", "shop_id");
                });

            modelBuilder.Entity("final_project.Models.Entities.Comment", b =>
                {
                    b.HasOne("final_project.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("product_id");

                    b.HasOne("final_project.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("final_project.Models.Entities.Order", b =>
                {
                    b.HasOne("final_project.Models.Entities.Payment_method", "Payment_Method")
                        .WithMany("Orders")
                        .HasForeignKey("payment_id");

                    b.HasOne("final_project.Models.Entities.Receiver", "Reciever")
                        .WithOne("Order")
                        .HasForeignKey("final_project.Models.Entities.Order", "receiver_id");

                    b.HasOne("final_project.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("final_project.Models.Entities.Order_detail", b =>
                {
                    b.HasOne("final_project.Models.Entities.Order", "Order")
                        .WithMany("Order_Details")
                        .HasForeignKey("order_id");

                    b.HasOne("final_project.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("product_id");
                });

            modelBuilder.Entity("final_project.Models.Entities.Product", b =>
                {
                    b.HasOne("final_project.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("cat_id");

                    b.HasOne("final_project.Models.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("shop_id");
                });

            modelBuilder.Entity("final_project.Models.Entities.Product_Color", b =>
                {
                    b.HasOne("final_project.Models.Entities.Color", "Color")
                        .WithMany("Product_Colors")
                        .HasForeignKey("color_id");

                    b.HasOne("final_project.Models.Entities.Product", "Product")
                        .WithMany("product_Colors")
                        .HasForeignKey("product_id");
                });

            modelBuilder.Entity("final_project.Models.Entities.Shop", b =>
                {
                    b.HasOne("final_project.Models.Entities.User", "User")
                        .WithOne("Shop")
                        .HasForeignKey("final_project.Models.Entities.Shop", "user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
